// Deliberate materials and compositions, rather than the same bouquet recolored.
// Each Atelier entry has its own primary motif, supporting detail and placement.
const atelier = {
  'rosalia-arch': ['floral/rose', 'romantic/ribbon', 'crest'],
  'peony-love-letter': ['floral/peony', 'vintage/seal', 'margin'],
  'magnolia-muse': ['floral/magnolia', 'modern/orbit', 'vertical'],
  'rosewood-nocturne': ['floral/camellia', 'celestial/constellation', 'orbit'],
  'sakura-serenade': ['floral/sakura', 'romantic/butterfly', 'canopy'],
  'orchid-royale': ['luxury/chandelier', 'floral/orchid', 'crest'],
  'champagne-correspondence': ['luxury/silk', 'vintage/seal', 'drape'],
  'fleur-de-palais': ['classical/fleur', 'luxury/gold-frame', 'vertical'],
  'velours-botanique': ['luxury/diamond', 'luxury/silk', 'orbit'],
  'pearl-blossom': ['luxury/pearl', 'floral/magnolia', 'margin'],
  'white-cosmos': ['modern/orbit', 'floral/cosmos', 'orbit'],
  'linen-blossom-letter': ['vintage/quill', 'modern/geometry', 'margin'],
  'eucalyptus-notes': ['botanical/eucalyptus', 'modern/geometry', 'vertical'],
  'moonstone-magnolia': ['modern/prism', 'celestial/light-ray', 'crest'],
  'petal-stillness': ['modern/geometry', 'floral/baby-breath', 'horizon'],
  'melati-keraton': ['nusantara/carved', 'floral/jasmine', 'crest'],
  'puspa-songket': ['nusantara/songket', 'luxury/gold-frame', 'margin'],
  'cempaka-pendopo': ['classical/column', 'nusantara/carved', 'vertical'],
  'anggrek-batik-malam': ['nusantara/kawung', 'luxury/pearl', 'orbit'],
  'kamboja-senja': ['nusantara/carved', 'botanical/palm', 'horizon'],
  'daisy-conservatory': ['botanical/vine', 'floral/daisy', 'canopy'],
  'wildflower-letters': ['floral/wildflower', 'vintage/quill', 'margin'],
  'fern-botanique': ['botanical/fern', 'botanical/olive', 'vertical'],
  'rose-garden-twilight': ['botanical/olive', 'celestial/light-ray', 'drape'],
  'meadow-butterfly': ['botanical/grass', 'romantic/butterfly', 'horizon'],
  'raudhah-bloom': ['islamic/arch', 'islamic/lantern', 'crest'],
  'jannah-letters': ['islamic/arabesque', 'vintage/quill', 'margin'],
  'maryam-garden': ['islamic/lantern', 'islamic/arabesque', 'vertical'],
  'noor-petals': ['islamic/crescent', 'celestial/light-ray', 'orbit'],
  'firdaus-breeze': ['islamic/arabesque', 'islamic/crescent', 'canopy'],
  'moonlit-garden': ['celestial/constellation', 'islamic/crescent', 'canopy'],
  'petal-nocturne': ['celestial/light-ray', 'vintage/seal', 'margin'],
  'bloom-premiere': ['modern/prism', 'celestial/light-ray', 'vertical'],
  'velvet-dusk': ['luxury/silk', 'celestial/constellation', 'drape'],
  'stella-flower': ['celestial/constellation', 'modern/orbit', 'orbit'],
  'rosette-postcard': ['vintage/postmark', 'vintage/quill', 'margin'],
  'lavender-correspondence': ['vintage/envelope', 'floral/lavender', 'crest'],
  'camellia-journal': ['vintage/quill', 'vintage/seal', 'vertical'],
  'butterfly-memoir': ['vintage/seal', 'romantic/butterfly', 'orbit'],
  'sakura-keepsake': ['vintage/vinyl', 'vintage/postmark', 'horizon'],
  'azure-orchid': ['nature/shell', 'nature/wave', 'crest'],
  'riviera-blossom-letter': ['nature/wave', 'vintage/postmark', 'margin'],
  'tropical-botanique': ['botanical/monstera', 'botanical/palm', 'canopy'],
  'coral-moonrise': ['nature/coral', 'celestial/constellation', 'orbit'],
  'island-petals': ['botanical/palm', 'nature/shell', 'horizon'],
  'pastel-carnival': ['romantic/balloon', 'romantic/ribbon', 'crest'],
  'flower-pop-letter': ['romantic/ribbon', 'vintage/envelope', 'margin'],
  'sakura-cloud': ['romantic/butterfly', 'modern/orbit', 'canopy'],
  'midnight-fiesta': ['modern/orbit', 'romantic/balloon', 'orbit'],
  'butterfly-confetti': ['romantic/butterfly', 'romantic/ribbon', 'horizon'],
  'fleur-geometry': ['modern/geometry', 'modern/prism', 'crest'],
  'botanical-signature': ['modern/mesh', 'botanical/eucalyptus', 'margin'],
  'urban-petal-editorial': ['modern/prism', 'modern/geometry', 'vertical'],
  'midnight-orchid': ['modern/orbit', 'modern/mesh', 'orbit'],
  'bloom-motion': ['modern/mesh', 'celestial/light-ray', 'horizon'],
}
const classic = {
  'romantic-floral': ['floral/rose', 'floral/baby-breath', 'canopy'],
  'elegant-luxury': ['luxury/chandelier', 'luxury/silk', 'drape'],
  'minimalist-white': ['classical/arch', 'modern/geometry', 'vertical'],
  'nusantara-heritage': ['nusantara/kawung', 'nusantara/carved', 'horizon'],
  'garden-dream': ['botanical/eucalyptus', 'floral/wildflower', 'canopy'],
  'classic-vintage': ['vintage/quill', 'vintage/postmark', 'margin'],
  'midnight-romance': ['celestial/constellation', 'floral/rose', 'orbit'],
  sakinah: ['islamic/arabesque', 'islamic/lantern', 'crest'],
  'eternal-story': ['celestial/light-ray', 'modern/prism', 'vertical'],
  blush: ['floral/peony', 'romantic/ribbon', 'canopy'],
  celestial: ['celestial/constellation', 'islamic/crescent', 'orbit'],
  editorial: ['modern/prism', 'luxury/gold-frame', 'vertical'],
  'ocean-vows': ['nature/wave', 'nature/shell', 'horizon'],
  'royal-heritage': ['classical/fleur', 'luxury/chandelier', 'crest'],
  'paper-petals': ['vintage/envelope', 'floral/baby-breath', 'margin'],
  botanica: ['botanical/monstera', 'botanical/eucalyptus', 'canopy'],
  monochrome: ['modern/geometry', 'classical/column', 'vertical'],
  'blossom-east': ['botanical/bamboo', 'floral/sakura', 'canopy'],
  'neon-love': ['modern/orbit', 'modern/prism', 'orbit'],
  'timeless-romance': ['classical/column', 'classical/fleur', 'crest'],
  'nur-jannah': ['islamic/arch', 'islamic/crescent', 'crest'],
  'mihrab-emerald': ['islamic/arabesque', 'islamic/arch', 'vertical'],
  'sahara-gold': ['nature/mountain', 'islamic/lantern', 'horizon'],
  'qamar-blue': ['islamic/crescent', 'islamic/arabesque', 'orbit'],
  'zahra-ivory': ['islamic/lantern', 'islamic/arch', 'canopy'],
  'rose-ribbon': ['romantic/ribbon', 'floral/rose', 'margin'],
  'linen-atelier': ['modern/geometry', 'vintage/quill', 'vertical'],
  'quiet-form': ['modern/prism', 'classical/arch', 'crest'],
  'ivory-grid': ['modern/mesh', 'modern/geometry', 'vertical'],
  'wayang-senja': ['nusantara/carved', 'islamic/lantern', 'vertical'],
  'batik-kencana': ['nusantara/kawung', 'luxury/gold-frame', 'crest'],
  'songket-raya': ['nusantara/songket', 'classical/fleur', 'horizon'],
  'aurora-glass': ['modern/orbit', 'celestial/light-ray', 'canopy'],
  'urban-signature': ['modern/mesh', 'luxury/diamond', 'vertical'],
  'riviera-postcard': ['vintage/postmark', 'nature/shell', 'margin'],
  'santorini-sky': ['classical/arch', 'nature/wave', 'horizon'],
  'desert-horizon': ['nature/mountain', 'celestial/light-ray', 'horizon'],
  'golden-atelier': ['luxury/gold-frame', 'luxury/diamond', 'crest'],
  'velvet-gala': ['luxury/silk', 'luxury/chandelier', 'drape'],
  'pearl-palace': ['luxury/pearl', 'classical/arch', 'crest'],
  'olive-grove': ['botanical/olive', 'floral/baby-breath', 'vertical'],
  'wildflower-meadow': ['floral/wildflower', 'botanical/grass', 'horizon'],
  'fern-serenade': ['botanical/fern', 'botanical/vine', 'canopy'],
  'glasshouse-morning': ['modern/mesh', 'botanical/vine', 'vertical'],
  'golden-hour': ['botanical/grass', 'celestial/light-ray', 'horizon'],
  'starlight-premiere': ['celestial/constellation', 'luxury/diamond', 'canopy'],
  'silver-screen': ['modern/prism', 'luxury/silk', 'vertical'],
  'motion-picture': ['celestial/light-ray', 'modern/orbit', 'orbit'],
  'sepia-memories': ['vintage/seal', 'vintage/quill', 'margin'],
  'postal-romance': ['vintage/envelope', 'vintage/postmark', 'margin'],
  'vinyl-vows': ['vintage/vinyl', 'vintage/seal', 'orbit'],
  'art-deco-letter': ['luxury/gold-frame', 'vintage/quill', 'vertical'],
  'confetti-club': ['romantic/ribbon', 'modern/orbit', 'canopy'],
  'balloon-fiesta': ['romantic/balloon', 'romantic/butterfly', 'crest'],
  'origami-dream': ['vintage/envelope', 'modern/prism', 'canopy'],
  'retro-festival': ['vintage/vinyl', 'romantic/balloon', 'horizon'],
}
const positions = {
  crest: ['tl', 'br'],
  margin: ['tr', 'bl'],
  vertical: ['tl', 'bl'],
  orbit: ['tr', 'br'],
  canopy: ['tl', 'tr'],
  drape: ['tr', 'bl'],
  horizon: ['bl', 'br'],
}
const split = (reference) => {
  const [family, name] = reference.split('/')
  return { family, name }
}
const atmosphere = {
  floral: ['petals', 'sparkles'],
  botanical: ['leaves', 'seeds'],
  luxury: ['sparkles'],
  modern: ['geometry', 'sparkles'],
  islamic: ['stars', 'sparkles'],
  nusantara: ['sparkles'],
  vintage: ['paper', 'sparkles'],
  nature: ['bubbles'],
  romantic: ['confetti', 'ribbons'],
  classical: ['sparkles'],
  celestial: ['stars', 'sparkles'],
}
export function artDirectionFor(key, config, collection = {}) {
  const nativeCorners = Boolean(atelier[key])
  const seed = [...(key || 'radina')].reduce(
    (sum, c) => (Math.imul(sum, 31) + c.codePointAt(0)) >>> 0,
    0,
  )
  const curated = atelier[key] || classic[key]
  const arrangement = curated?.[2] || Object.keys(positions)[seed % 7]
  const primary = split(
    curated?.[0] || `${config.ornamentFamily}/${config.ornament}`,
  )
  const accent = split(
    curated?.[1] || `${config.ornamentFamily}/${config.secondaryOrnament}`,
  )
  return {
    id: key || 'radina',
    primary,
    accent,
    effects: config.sceneProfile?.cinematic
      ? config.sceneProfile.effects
      : primary.name === 'balloon'
        ? ['balloons', 'confetti']
        : atmosphere[primary.family] || ['sparkles'],
    arrangement,
    nativeCorners,
    corners: positions[arrangement],
    // Color, layout and content stay in the original catalog. Decoration is sparse.
    treatment: config.personality,
    family: collection.family || config.layout,
    signature: [
      primary.family,
      primary.name,
      accent.family,
      accent.name,
      arrangement,
      collection.family || config.layout,
    ].join('/'),
  }
}
