<?php

namespace App\Services;

class TemplateCatalog
{
    public const KEYS = ['romantic-floral', 'elegant-luxury', 'minimalist-white', 'nusantara-heritage', 'garden-dream', 'classic-vintage', 'midnight-romance', 'sakinah', 'eternal-story', 'blush', 'celestial', 'editorial', 'ocean-vows', 'royal-heritage', 'paper-petals', 'botanica', 'monochrome', 'blossom-east', 'neon-love', 'timeless-romance', 'nur-jannah', 'mihrab-emerald', 'sahara-gold', 'qamar-blue', 'zahra-ivory', 'rose-ribbon', 'linen-atelier', 'quiet-form', 'ivory-grid', 'wayang-senja', 'batik-kencana', 'songket-raya', 'aurora-glass', 'urban-signature', 'riviera-postcard', 'santorini-sky', 'desert-horizon', 'golden-atelier', 'velvet-gala', 'pearl-palace', 'olive-grove', 'wildflower-meadow', 'fern-serenade', 'glasshouse-morning', 'golden-hour', 'starlight-premiere', 'silver-screen', 'motion-picture', 'sepia-memories', 'postal-romance', 'vinyl-vows', 'art-deco-letter', 'confetti-club', 'balloon-fiesta', 'origami-dream', 'retro-festival'];

    public const COMPONENTS = ['RomanticFloralTemplate.vue', 'RomanticFloral.vue', 'ElegantLuxury.vue', 'MinimalistWhite.vue', 'NusantaraHeritage.vue', 'GardenDream.vue', 'ClassicVintage.vue', 'MidnightRomance.vue', 'Sakinah.vue', 'EternalStory.vue', 'Blush.vue', 'Celestial.vue', 'Editorial.vue', 'OceanVows.vue', 'RoyalHeritage.vue', 'PaperPetals.vue', 'Botanica.vue', 'Monochrome.vue', 'BlossomEast.vue', 'NeonLove.vue', 'TimelessRomance.vue', 'NurJannah.vue', 'MihrabEmerald.vue', 'SaharaGold.vue', 'QamarBlue.vue', 'ZahraIvory.vue', 'RoseRibbon.vue', 'LinenAtelier.vue', 'QuietForm.vue', 'IvoryGrid.vue', 'WayangSenja.vue', 'BatikKencana.vue', 'SongketRaya.vue', 'AuroraGlass.vue', 'UrbanSignature.vue', 'RivieraPostcard.vue', 'SantoriniSky.vue', 'DesertHorizon.vue', 'GoldenAtelier.vue', 'VelvetGala.vue', 'PearlPalace.vue', 'OliveGrove.vue', 'WildflowerMeadow.vue', 'FernSerenade.vue', 'GlasshouseMorning.vue', 'GoldenHour.vue', 'StarlightPremiere.vue', 'SilverScreen.vue', 'MotionPicture.vue', 'SepiaMemories.vue', 'PostalRomance.vue', 'VinylVows.vue', 'ArtDecoLetter.vue', 'ConfettiClub.vue', 'BalloonFiesta.vue', 'OrigamiDream.vue', 'RetroFestival.vue'];
}
