import { defineAsyncComponent } from 'vue'
export const templateRegistry = {
  'timeless-romance': defineAsyncComponent(() => import('./TimelessRomance/index.vue')),
  'neon-love': defineAsyncComponent(() => import('./NeonLove/index.vue')),
  'blossom-east': defineAsyncComponent(() => import('./BlossomEast/index.vue')),
  monochrome: defineAsyncComponent(() => import('./Monochrome/index.vue')),
  botanica: defineAsyncComponent(() => import('./Botanica/index.vue')),
  'paper-petals': defineAsyncComponent(() => import('./PaperPetals/index.vue')),
  'royal-heritage': defineAsyncComponent(() => import('./RoyalHeritage/index.vue')),
  'ocean-vows': defineAsyncComponent(() => import('./OceanVows/index.vue')),
  editorial: defineAsyncComponent(() => import('./Editorial/index.vue')),
  celestial: defineAsyncComponent(() => import('./Celestial/index.vue')),
  'romantic-floral': defineAsyncComponent(() => import('./RomanticFloral/index.vue')),
  'elegant-luxury': defineAsyncComponent(() => import('./ElegantLuxury/index.vue')),
  'minimalist-white': defineAsyncComponent(() => import('./MinimalistWhite/index.vue')),
  'nusantara-heritage': defineAsyncComponent(() => import('./NusantaraHeritage/index.vue')),
  'garden-dream': defineAsyncComponent(() => import('./GardenDream/index.vue')),
  'classic-vintage': defineAsyncComponent(() => import('./ClassicVintage/index.vue')),
  'midnight-romance': defineAsyncComponent(() => import('./MidnightRomance/index.vue')),
  sakinah: defineAsyncComponent(() => import('./Sakinah/index.vue')),
  'eternal-story': defineAsyncComponent(() => import('./EternalStory/index.vue')),
  blush: defineAsyncComponent(() => import('./Blush/index.vue')),
}
export const templateOptions = [
  { value: 'timeless-romance', label: 'Timeless Romance', component: 'TimelessRomance.vue' },
  { value: 'neon-love', label: 'Neon Love', component: 'NeonLove.vue' },
  { value: 'blossom-east', label: 'Blossom East', component: 'BlossomEast.vue' },
  { value: 'monochrome', label: 'Monochrome', component: 'Monochrome.vue' },
  { value: 'botanica', label: 'Botanica', component: 'Botanica.vue' },
  { value: 'paper-petals', label: 'Paper & Petals', component: 'PaperPetals.vue' },
  { value: 'royal-heritage', label: 'Royal Heritage', component: 'RoyalHeritage.vue' },
  { value: 'ocean-vows', label: 'Ocean Vows', component: 'OceanVows.vue' },
  { value: 'editorial', label: 'Editorial', component: 'Editorial.vue' },
  { value: 'celestial', label: 'Celestial', component: 'Celestial.vue' },
  { value: 'romantic-floral', label: 'Amore Bloom', component: 'RomanticFloral.vue' },
  { value: 'elegant-luxury', label: 'Noir Élégance', component: 'ElegantLuxury.vue' },
  { value: 'minimalist-white', label: 'Pure', component: 'MinimalistWhite.vue' },
  { value: 'nusantara-heritage', label: 'Nusantara', component: 'NusantaraHeritage.vue' },
  { value: 'garden-dream', label: 'Verdant Vows', component: 'GardenDream.vue' },
  { value: 'classic-vintage', label: 'Heritage Letters', component: 'ClassicVintage.vue' },
  { value: 'midnight-romance', label: 'After Dark', component: 'MidnightRomance.vue' },
  { value: 'sakinah', label: 'Sakinah', component: 'Sakinah.vue' },
  { value: 'eternal-story', label: 'Frame by Frame', component: 'EternalStory.vue' },
  { value: 'blush', label: 'Daydream', component: 'Blush.vue' },
]
