<?php

use App\Http\Controllers\AdminCustomerPortalController;
use App\Http\Controllers\AdminGiftController;
use App\Http\Controllers\AdminInviteeController;
use App\Http\Controllers\AdminMusicController;
use App\Http\Controllers\AdminOrderController;
use App\Http\Controllers\AdminSettingsController;
use App\Http\Controllers\AdminTemplateController;
use App\Http\Controllers\AdminWeddingController;
use App\Http\Controllers\AdminWeddingImportController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\CustomerPortalController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\LicenseAdminController;
use App\Http\Controllers\MediaController;
use App\Http\Controllers\SiteController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

// Administrator endpoints always use web sessions and CSRF, independent of Sanctum's domain list.
Route::prefix('api/admin')->middleware('throttle:api')->group(function () {
    Route::get('/captcha', [AuthController::class, 'captcha'])->middleware('throttle:admin-captcha');
    Route::post('/login', [AuthController::class, 'login'])->middleware('throttle:admin-login');
    Route::middleware(['auth:sanctum', 'admin'])->group(function () {
        Route::get('/packages', [\App\Http\Controllers\PackageController::class, 'index']);
        Route::post('/packages', [\App\Http\Controllers\PackageController::class, 'savePackage']);
        Route::put('/packages/{package}', [\App\Http\Controllers\PackageController::class, 'savePackage']);
        Route::post('/addons', [\App\Http\Controllers\PackageController::class, 'saveAddon']);
        Route::put('/addons/{addon}', [\App\Http\Controllers\PackageController::class, 'saveAddon']);
        Route::get('/reminders', [\App\Http\Controllers\ReminderController::class, 'index']);
        Route::patch('/reminders/{reminder}', [\App\Http\Controllers\ReminderController::class, 'update']);
        Route::get('/orders/{order}/documents/{type}', [\App\Http\Controllers\OrderDocumentController::class, 'admin'])->whereIn('type', ['invoice', 'receipt']);
        Route::get('/weddings/{wedding}/analytics', [\App\Http\Controllers\InvitationToolsController::class, 'analytics']);
        Route::get('/weddings/{wedding}/guest-statistics', [\App\Http\Controllers\InvitationToolsController::class, 'guests']);
        Route::post('/weddings/{wedding}/check-in/lookup', [\App\Http\Controllers\InvitationToolsController::class, 'lookup']);
        Route::post('/weddings/{wedding}/check-in', [\App\Http\Controllers\InvitationToolsController::class, 'checkIn']);
        Route::get('/licenses', [LicenseAdminController::class, 'index']);
        Route::post('/licenses', [LicenseAdminController::class, 'store']);
        Route::patch('/licenses/{license}', [LicenseAdminController::class, 'update']);
        Route::patch('/licenses/{license}/toggle-status', [LicenseAdminController::class, 'toggleStatus']);
        Route::delete('/licenses/{license}', [LicenseAdminController::class, 'destroy']);
        Route::get('/me', [AuthController::class, 'me']);
        Route::get('/music', [AdminMusicController::class, 'index']);
        Route::post('/music', [AdminMusicController::class, 'store']);
        Route::put('/music/{music}', [AdminMusicController::class, 'update']);
        Route::delete('/music/{music}', [AdminMusicController::class, 'destroy']);
        Route::post('/logout', [AuthController::class, 'logout']);
        Route::get('/dashboard', [AdminOrderController::class, 'dashboard']);
        Route::get('/orders', [AdminOrderController::class, 'index']);
        Route::get('/orders/{order}', [AdminOrderController::class, 'show']);
        Route::patch('/orders/{order}/payment', [AdminOrderController::class, 'payment']);
        Route::patch('/orders/{order}/status', [AdminOrderController::class, 'status']);
        Route::post('/orders/{order}/wedding', [AdminOrderController::class, 'wedding']);
        Route::get('/weddings/{wedding}', [AdminWeddingController::class, 'show']);
        Route::put('/weddings/{wedding}', [AdminWeddingController::class, 'update']);
        Route::get('/weddings/{wedding}/preview', [AdminWeddingController::class, 'show']);
        Route::post('/weddings/{wedding}/publish', [AdminWeddingController::class, 'publish']);
        Route::get('/weddings/{wedding}/customer-portal', [AdminCustomerPortalController::class, 'show']);
        Route::post('/weddings/{wedding}/customer-portal', [AdminCustomerPortalController::class, 'issue']);
        Route::delete('/weddings/{wedding}/customer-portal', [AdminCustomerPortalController::class, 'revoke']);
        Route::post('/weddings/{wedding}/customer-portal/apply', [AdminCustomerPortalController::class, 'apply']);
        Route::post('/weddings/{wedding}/customer-portal/review', [AdminCustomerPortalController::class, 'review']);
        Route::get('/weddings/{wedding}/content/template', [AdminWeddingImportController::class, 'template']);
        Route::get('/weddings/{wedding}/content/export', [AdminWeddingImportController::class, 'export']);
        Route::post('/weddings/{wedding}/content/preview', [AdminWeddingImportController::class, 'preview']);
        Route::post('/weddings/{wedding}/content/import', [AdminWeddingImportController::class, 'store']);
        Route::get('/weddings/{wedding}/invitees/template', [AdminInviteeController::class, 'template']);
        Route::get('/weddings/{wedding}/invitees/export', [AdminInviteeController::class, 'export']);
        Route::get('/weddings/{wedding}/invitees', [AdminInviteeController::class, 'index']);
        Route::post('/weddings/{wedding}/invitees/preview', [AdminInviteeController::class, 'preview']);
        Route::post('/weddings/{wedding}/invitees/import', [AdminInviteeController::class, 'store']);
        Route::delete('/weddings/{wedding}/invitees/{invitee}', [AdminInviteeController::class, 'destroy']);
        Route::get('/weddings/{wedding}/gifts', [AdminGiftController::class, 'index']);
        Route::post('/weddings/{wedding}/gifts', [AdminGiftController::class, 'store']);
        Route::patch('/weddings/{wedding}/gifts/reorder', [AdminGiftController::class, 'reorder']);
        Route::put('/weddings/{wedding}/gifts/{gift}', [AdminGiftController::class, 'update']);
        Route::delete('/weddings/{wedding}/gifts/{gift}', [AdminGiftController::class, 'destroy']);
        Route::get('/weddings/{wedding}/rsvps', [AdminWeddingController::class, 'rsvps']);
        Route::get('/weddings/{wedding}/wishes', [AdminWeddingController::class, 'wishes']);
        Route::patch('/weddings/{wedding}/wishes/{wish}', [AdminWeddingController::class, 'moderate']);
        Route::post('/media', [MediaController::class, 'store']);
        Route::get('/templates', [AdminTemplateController::class, 'index']);
        Route::post('/templates', [AdminTemplateController::class, 'store']);
        Route::put('/templates/{template}', [AdminTemplateController::class, 'update']);
        Route::get('/settings', [AdminSettingsController::class, 'show']);
        Route::put('/settings', [AdminSettingsController::class, 'update']);
    });
});

Route::prefix('api/customer-portals/{token}')->middleware('throttle:api')->group(function () {
    Route::get('/documents/{type}', [CustomerPortalController::class, 'document'])->whereIn('type', ['invoice', 'receipt']);
    Route::get('/analytics', [CustomerPortalController::class, 'analytics']);
    Route::get('/guest-statistics', [CustomerPortalController::class, 'guests']);
    Route::get('/reminders', [CustomerPortalController::class, 'reminders']);
    Route::get('/', [CustomerPortalController::class, 'show']);
    Route::put('/', [CustomerPortalController::class, 'save']);
    Route::get('/preview', [CustomerPortalController::class, 'preview']);
    Route::post('/response', [CustomerPortalController::class, 'respond']);
    Route::post('/media', [CustomerPortalController::class, 'media']);
});

Route::get('/assets/{file}', [SiteController::class, 'asset']);
Route::get('/storage/{file}', [SiteController::class, 'media'])->where('file', '.*');
Route::get('/favicon.svg', fn () => response()->file(base_path('frontend/public/favicon.svg'), ['Content-Type' => 'image/svg+xml']));
Route::get('/login', fn () => redirect('/admin/login'))->name('login');
Route::get('/dashboard', fn (Request $request) => redirect($request->query('section') === 'licenses' ? '/admin/licenses' : '/admin'))->name('dashboard');
Route::middleware(['auth', 'admin'])->group(function () {
    Route::post('/licenses', [DashboardController::class, 'store'])->name('licenses.store');
    Route::patch('/licenses/{license}', [DashboardController::class, 'update'])->name('licenses.update');
    Route::delete('/licenses/{license}', [DashboardController::class, 'destroy'])->name('licenses.destroy');
    Route::patch('/licenses/{license}/toggle-status', [DashboardController::class, 'toggleStatus'])->name('licenses.toggle-status');
});
Route::get('/sitemap.xml', [SiteController::class, 'sitemap']);
Route::get('/robots.txt', [SiteController::class, 'robots']);
Route::get('/berita/{any?}', [SiteController::class, 'retired'])->where('any', '.*');
Route::get('/kategori/{any?}', [SiteController::class, 'retired'])->where('any', '.*');
Route::get('/topik/{any?}', [SiteController::class, 'retired'])->where('any', '.*');
Route::get('/news-sitemap.xml', [SiteController::class, 'retired']);
Route::get('/rss.xml', [SiteController::class, 'retired']);
Route::get('/brand/{file}', [SiteController::class, 'brand']);
Route::get('/images/templates/{file}', [SiteController::class, 'thumbnail']);
Route::get('/images/bouquets/{file}', [SiteController::class, 'bouquetImage']);
Route::get('/bucket', fn () => redirect('/buket', 301));
Route::get('/w/{slug}', [SiteController::class, 'wedding']);
Route::get('/{any?}', [SiteController::class, 'index'])->where('any', '^(?!api(?:/|$)|storage(?:/|$)|sanctum(?:/|$)|assets(?:/|$)).*');
